config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/destroy'

  get 'usrs/index'

  get 'signup' , to: 'usrs#new'

  get 'usrs/create'

  get 'usrs/edit'

  get 'usrs/update'

  get 'usrs/destroy'

  

  get 'about' => 'about#index'

  get "contacts" => 'contacts#new'

  get 'contacts/create'

  namespace :admin do
  get 'login' => 'sessions#new' ,  :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy' ,  :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts , :categories , :usrs , :sessions

  resources "contacts" , only: [:new, :create] 

  namespace :admin do
    resources :posts , :categories , :comments , :users, :sessions

  end

  resources :post do
    resources :comments
  end


  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get 'logout' , to: 'sessions#destroy'
 
 root 'posts#index'



end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

	validates :name , presence: true

	def self.search(query)
		where("name like  ? ","%#{query}%")
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :comments
	belongs_to :usr
	validates :title , presence: true
	validates :category_id , presence: true
	validates :body , presence: true

	has_attached_file :image , :default_url => ':style/rails.png'
	validates_attachment_content_type :image , :content_type => /\Aimage\/.*\Z/


	def self.search(query)
		where("title like  ? OR body like ?","%#{query}%","%#{query}%")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password
	has_many :posts

	validates :name , presence: { message: ": Veuillez Saisir votre Nom, svp..." }
	validates :email , presence: { message: ": Veuillez Saisir votre email, svp..." }
	validates :password , presence: { message: ": Veuillez Saisir votre pwd, svp..." }
	validates :password , confirmation: { message: ": Veuillez Saisir à Nouveau votre pwd, svp..." }

	#has_attached_file :image , :default_url => ':style/index.png'
	#validates_attachment_content_type :image , :content_type => /\Aimage\/.*\Z/


	def self.authenticate(email, password) #pwd et mail donnés
		user = find_by_email(email) # verif si prensant en base
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user                 #verif si pwd donné correspond à celui en base
		else
			nil
		end
	end
	 

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def self.search(query)
		where("name like  ? OR email like ?","%#{query}%","%#{query}%")
	end

end

app/models/usr.rb
class Usr < ActiveRecord::Base
	has_many :posts

	before_save {self.email = email.downcase}

	validates_length_of :username,
		  :within => 3..25,
		  :too_short => 'Votre nom doit avoir au moins 3 caratères',
		  :too_long => 'Votre nom doit avoir au plus 25 caratères'

	
   validates :username, presence: true, uniqueness: {case_sensitive: false}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, uniqueness: {case_sensitive: false},
   				format: {with: VALID_EMAIL_REGEX }

   	has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@categories = Category.all
  	@category = Category.find(params[:id])
  	@posts = @category.posts
  end

  def index
  	if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at desc').paginate(:per_page => 2, :page => params[:page]) 
    else
      @categories = Category.all.order('created_at desc').paginate(:per_page => 2, :page => params[:page])
    end
  	@categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comment_params)
  	flash[:notice] = 'Commentaire ajouté'
  	redirect_to post_path(@post)
  end
  private
  	def comment_params
  		params.require(:comment).permit(:name,:email,:body,:post_id)
  	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
  	if params[:search]
      @posts = Post.all.order('created_at desc').paginate(:per_page => 2, :page => params[:page]) 
    else
      @posts = Post.all.order('created_at desc').paginate(:per_page => 1, :page => params[:page]) 
    end
  	
  end

  def show
  	@post = Post.find(params[:id])
  	@comments = Comment.all
  	@comment = Comment.new
  	@categories = Category.all
    @u = @post.usr
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	layout 'admin/login'
  def new
  end

  def create
  	 user = Usr.find_by(email: params[:session][:email].downcase)
  	 if user && user.authenticate(params[:session][:password])
  	 	session[:user_id] = user.id
  	 	
  	 	flash[:notice] = 'Bienvenu sur rBlog'
  	 	redirect_to usr_path(user)
  	 else
  	 	flash.now[:alert] = 'Login ou mot de passe incorrecte'
  	 	render 'new'
  	 end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:notice] = "Vous vous etes deconnecter..."
  	redirect_to root_path
  end
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]
  before_action :require_user ,except: [:show,:index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = Usr.all
  end

  def show
    
  end

  def new
    @user = Usr.new
  end

  def create
    @user = Usr.new(user_params)

    if @user.save
      flash[:notice] = "Bienvenu à rB.com, #{@user.username}..."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    

    if @user.update(user_params)
      flash[:notice] = "Mise à jour Réussie..."
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
  end
  private
    def user_params
      params.require(:usr).permit(:username,:email,:password)
    end

    def set_user
      @user = Usr.find(params[:id])
    end

    def require_same_user
     if current_user != @user
        flash[:alert] = "Vous n'etes pas autorisé à effectuer cette opération..." 
        redirect_to root_path
     end
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, option = {size: 80})
		size = option[:size]
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}/?s=#{size}"
		image_tag(gravatar_url , alt:user.username , class:"img-circle")
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBlog</title>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
	

<nav class="nav navbar-default">
<div class="container-fluid">
<div class="navbar-header"><a class="navbar-brand" href="<%= admin_posts_path%>"><h1>rBlog<span>/Manager/</span></h1></a></div>
<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav">
		<li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>">
      <%= link_to "Posts" , admin_posts_path %></li>

		
    <li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>">
          <%= link_to "Categories" , admin_categories_path %></li>

		  <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>">
              <%= link_to "Users" , admin_users_path %></li>

	</ul>
	
  <%= render 'partials/admin/search'  %>


</div>
</div>
</nav>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <div class="pull-right" id="user_nav">
          <% if current_user %>
            Logged in as <%= current_user.email %>
            <%= link_to "Deconnexion" , admin_logout_path %>
          <%else%>
            <%= link_to "Connexion" , admin_login_path %>
          <%end%>
        </div>
        
          <%= render 'partials/flash' %>

          <%= yield %>

        </div>
      
    </div>
  </div>
</div>


<%= render 'partials/admin/footer' %>
</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login | RBlog</title>
  <%= stylesheet_link_tag    'admin/login', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>


</head>
<body>
  <div class="container-fluid">
    <%= yield %>

  </div>
  <%= debug(params) %>
</body>
</html>

app/views/partials/admin/_footer.html.erb
<footer>
	<p>Copyright &copy; 2015, rBlog | <%=  link_to "FrontEnd" , root_path %></p>
</footer>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == "admin/posts" %>
  <%= form_tag(admin_posts_path, :method => "get" , :id => "search-form" , class:"search-form pull-right" ) do %>
      <div class="form-group">
        <%=  text_field_tag :search , params[:search] , placeholder: "Search Posts" , class:"form-control" %>
      </div>
      
      <%= submit_tag "Search" , :name => nil , class:'btn btn-primary'   %>
  <% end %>
<% elsif params[:controller] == "admin/categories" %>
  <%= form_tag(admin_categories_path, :method => "get" , :id => "search-form" , class:"search-form pull-right" ) do %>
      <div class="form-group">
        <%=  text_field_tag :search , params[:search] , placeholder: "Search Categories" , class:"form-control" %>
      </div>
      
      <%= submit_tag "Search" , :name => nil , class:'btn btn-primary'   %>
  <% end %>
<% else %>
  <%= form_tag(admin_users_path, :method => "get" , :id => "search-form" , class:"search-form pull-right" ) do %>
      <div class="form-group">
        <%=  text_field_tag :search , params[:search] , placeholder: "Search Users" , class:"form-control" %>
      </div>
      
      <%= submit_tag "Search" , :name => nil , class:'btn btn-primary'   %>
  <% end %>
<% end %>