config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/destroy'

  get 'usrs/index'

  get 'signup' , to: 'usrs#new'

  get 'usrs/create'

  get 'usrs/edit'

  get 'usrs/update'

  get 'usrs/destroy'

  

  get 'about' => 'about#index'

  get "contacts" => 'contacts#new'

  get 'contacts/create'

  namespace :admin do
  get 'login' => 'sessions#new' ,  :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy' ,  :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts , :categories , :usrs , :sessions

  resources "contacts" , only: [:new, :create] 

  namespace :admin do
    resources :posts , :categories , :comments , :users, :sessions

  end

  resources :post do
    resources :comments
  end


  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get 'logout' , to: 'sessions#destroy'
 
 root 'posts#index'



end

app/models/usr.rb
class Usr < ActiveRecord::Base
	has_many :posts

	before_save {self.email = email.downcase}

	validates_length_of :username,
		  :within => 3..25,
		  :too_short => 'Votre nom doit avoir au moins 3 caratères',
		  :too_long => 'Votre nom doit avoir au plus 25 caratères'

	
   validates :username, presence: true, uniqueness: {case_sensitive: false}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, uniqueness: {case_sensitive: false},
   				format: {with: VALID_EMAIL_REGEX }

   	has_secure_password
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]
  before_action :require_user ,except: [:show,:index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = Usr.all
  end

  def show
    
  end

  def new
    @user = Usr.new
  end

  def create
    @user = Usr.new(user_params)

    if @user.save
      flash[:notice] = "Bienvenu à rB.com, #{@user.username}..."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    

    if @user.update(user_params)
      flash[:notice] = "Mise à jour Réussie..."
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
  end
  private
    def user_params
      params.require(:usr).permit(:username,:email,:password)
    end

    def set_user
      @user = Usr.find(params[:id])
    end

    def require_same_user
     if current_user != @user
        flash[:alert] = "Vous n'etes pas autorisé à effectuer cette opération..." 
        redirect_to root_path
     end
    end
end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/usrs/_form.html.erb
<%= form_for [@user] do |f| %>
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |m| %>
		<div class="alert alert-danger"><%= m %></div>
	<%end%> <!-- end Do m -->
<%end%> <!-- end If -->
<div >
	<%= f.label :'Nom Utilisateur' %>
	<%= f.text_field :username,class:'form-control', placeholder:'Entrez votre Nom et Prénom' ,autofocus: true %>
</div>

<div >
	<%= f.label :Email %>
	<%= f.email_field :email,class:'form-control' ,placeholder:'Entrez votre adresse mail' ,autofocus: true%>
</div>

<div >
	<%= f.label :'Mot de passe' %>
	<%= f.password_field :password,class:'form-control', placeholder:'Entrez votre Mot de Passe', autofocus: true%>
</div>


<br>

<div ><%= f.submit "Valider" , class:'btn btn-primary'  %>
	<%=  link_to "Annuler" , usrs_path, class:'btn btn-default' %></div>
<%end%> <!-- end Do f -->

app/views/usrs/create.html.erb
<h1>Usrs#create</h1>
<p>Find me in app/views/usrs/create.html.erb</p>

app/views/usrs/destroy.html.erb
<h1>Usrs#destroy</h1>
<p>Find me in app/views/usrs/destroy.html.erb</p>

app/views/usrs/edit.html.erb
<h3 align="center">Modification du Profile</h3>
<%= render 'form' %>

app/views/usrs/index.html.erb
<h1 align="center">Liste des blogeurs du site web rBlog.com</h1>

<div align="center"><% @users.each do |u| %>
		<ul class="listing">
			<div class="row">
				<div class=" well col-md-4 col-md-offset-4">
					<li><%= link_to gravatar_for(u) , usr_path(u)  %></li>
					<li class="post-title"><%= link_to u.username, usr_path(u) %></li>
					<li><small><%= pluralize(u.posts.count, "post") if u.posts %></small></li>
				</div>
			</div>
		</ul>
	<%end%>
</div>

app/views/usrs/new.html.erb
<h2 align="center">Inscription</h2>
<%= render 'form' %>

app/views/usrs/show.html.erb
<h3 align="center">Bienvenu sur le profil  de <%= @user.username %></h3>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<h4 align="left">Posts Publiés par <%= @user.username %></h4>

<%= render 'posts/post' , obj: @user.posts %>

app/views/usrs/update.html.erb
<h1>Usrs#update</h1>
<p>Find me in app/views/usrs/update.html.erb</p>