config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/destroy'

  get 'usrs/index'

  get 'signup' , to: 'usrs#new'

  get 'usrs/create'

  get 'usrs/edit'

  get 'usrs/update'

  get 'usrs/destroy'

  

  get 'about' => 'about#index'

  get "contacts" => 'contacts#new'

  get 'contacts/create'

  namespace :admin do
  get 'login' => 'sessions#new' ,  :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy' ,  :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts , :categories , :usrs , :sessions

  resources "contacts" , only: [:new, :create] 

  namespace :admin do
    resources :posts , :categories , :comments , :users, :sessions

  end

  resources :post do
    resources :comments
  end


  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get 'logout' , to: 'sessions#destroy'
 
 root 'posts#index'



end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

	validates :name , presence: true

	def self.search(query)
		where("name like  ? ","%#{query}%")
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :verify_logged_in
  before_action :set_category , [:edit , :update , :show , :destroy ]

  def new
    @category = Category.new  
    
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Catégorie créee'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    
    if @category.update(category_params)
      flash[:notice] = 'Mise à Réussie'
      redirect_to admin_categories_path
    else
      
      render 'new'
    end
  end

  def destroy
    
    @category.destroy
    flash[:notice] = 'Supression Réussie'
      redirect_to admin_categories_path
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at desc').paginate(:per_page => 2, :page => params[:page]) 
    else
      @categories = Category.all.order('created_at desc').paginate(:per_page => 2, :page => params[:page])
    end

  end

  def show
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@categories = Category.all
  	@category = Category.find(params[:id])
  	@posts = @category.posts
  end

  def index
  	if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at desc').paginate(:per_page => 2, :page => params[:page]) 
    else
      @categories = Category.all.order('created_at desc').paginate(:per_page => 2, :page => params[:page])
    end
  	@categories = Category.all
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2>Mise &agrave; Jour de Catégorie</h2>
<%= form_for [:admin, @category] do |f| %>
<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |m| %>
		<div class="alert alert-danger"><%= m %></div>
	<%end%> <!-- end Do m -->
<%end%> <!-- end If -->
<div class="form-group"><%= f.label :name %><%= f.text_field :name,class:'form-control' %></div>
<br>
<%= f.submit "Submit" , class:'btn btn-primary'  %>
<%=  link_to "Cancel" , admin_categories_path, class:'btn btn-default' %>
<%end%> <!-- end Do f -->

app/views/admin/categories/index.html.erb
<h2 class="page-header">Manage Categories  
<%=  link_to "Add New" , new_admin_category_path , class:"btn btn-success pull-right" %>
</h2>
<%if @categories.exists? %>
<table class="table table-striped">
	<tr>
		<th>Category Title</th>
		<th>Created Date</th>
		<th>Actions</th>
	</tr>
	<% @categories.each do |c| %>
	<tr>
		<td><%=c.name%></td>
		<td><%= c.created_at.to_time.strftime('%e %B à %l:%M %p')%></td>			
		<td>
			<%= link_to "Edit" , edit_admin_category_path(c) , class:'btn btn-primary' %>  
		<%= link_to "Delete" , admin_category_path(c) , class:'btn btn-danger' , method: :delete , data: {confirm:"Confirmez cette suppression..."} %></td>
		
	</tr>
	<%end%>
</table>
<%= will_paginate @categories %>
<%else%>
	<p>Aucune Categorie</p>
<%end%>

app/views/admin/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for [:admin, @category] do |f| %>
<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |m| %>
		<div class="alert alert-danger"><%= m %></div>
	<%end%> <!-- end Do m -->
<%end%> <!-- end If -->
<div class="form-group"><%= f.label :name %><%= f.text_field :name,class:'form-control' %></div>
<br>
<%= f.submit "Submit" , class:'btn btn-primary'  %>
<%=  link_to "Cancel" , admin_categories_path, class:'btn btn-default' %>
<%end%> <!-- end Do f -->