config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/destroy'

  get 'usrs/index'

  get 'signup' , to: 'usrs#new'

  get 'usrs/create'

  get 'usrs/edit'

  get 'usrs/update'

  get 'usrs/destroy'

  

  get 'about' => 'about#index'

  get "contacts" => 'contacts#new'

  get 'contacts/create'

  namespace :admin do
  get 'login' => 'sessions#new' ,  :as => 'login'
  end

  namespace :admin do
  get 'logout' => 'sessions#destroy' ,  :as => 'logout'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts , :categories , :usrs , :sessions

  resources "contacts" , only: [:new, :create] 

  namespace :admin do
    resources :posts , :categories , :comments , :users, :sessions

  end

  resources :post do
    resources :comments
  end


  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get 'logout' , to: 'sessions#destroy'
 
 root 'posts#index'



end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password
	has_many :posts

	validates :name , presence: { message: ": Veuillez Saisir votre Nom, svp..." }
	validates :email , presence: { message: ": Veuillez Saisir votre email, svp..." }
	validates :password , presence: { message: ": Veuillez Saisir votre pwd, svp..." }
	validates :password , confirmation: { message: ": Veuillez Saisir à Nouveau votre pwd, svp..." }

	#has_attached_file :image , :default_url => ':style/index.png'
	#validates_attachment_content_type :image , :content_type => /\Aimage\/.*\Z/


	def self.authenticate(email, password) #pwd et mail donnés
		user = find_by_email(email) # verif si prensant en base
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user                 #verif si pwd donné correspond à celui en base
		else
			nil
		end
	end
	 

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def self.search(query)
		where("name like  ? OR email like ?","%#{query}%","%#{query}%")
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_filter :verify_logged_in
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    

    if @user.save
      flash[:notice] = 'User crée'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id]) # Variable pour charger le formulaire de modification*/
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Mise à Jour Réussie'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'Supression Réussie'
      redirect_to admin_users_path
  end

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at desc').paginate(:per_page => 2, :page => params[:page]) 
    else
      @users = User.all.order('created_at desc').paginate(:per_page => 2, :page => params[:page])
    end 
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>Mise à Jour Paramettres User</h2>
<%= form_for [:admin, @user] do |f| %>
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |m| %>
		<div class="alert alert-danger"><%= m %></div>
	<%end%> <!-- end Do m -->
<%end%> <!-- end If -->
<div class="form-group col-md-4 pull-left">
	<%= f.label :'Nom Utilisateur' %>
	<%= f.text_field :name,class:'form-control' %>
</div>

<div class="form-group col-md-4 pull-left">
	<%= f.label :Email %>
	<%= f.text_field :email,class:'form-control' %>
</div>

<div class="form-group col-md-4 pull-left">
	<%= f.label :'Mot de passe' %>
	<%= f.password_field :password,class:'form-control' %>
</div>

<div class="form-group col-md-4 pull-left">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation,class:'form-control' %>
</div>
<br>

<div class="form-group col-md-4 pull-right"><%= f.submit "Submit" , class:'btn btn-primary'  %>
	<%=  link_to "Cancel" , admin_users_path, class:'btn btn-default' %></div>
<%end%> <!-- end Do f -->

app/views/admin/users/index.html.erb
<h2 class="page-header">Manage Users  
<%=  link_to "Add New" , new_admin_user_path , class:"btn btn-success pull-right" %>
</h2>
<%if @users.exists? %>
<table class="table table-striped">
	<tr>
		<th>Nom Utilisateur</th>
		<th>Email</th>
		<th>Created Date</th>
		<th>Actions</th>
	</tr>
	<% @users.each do |c| %>
	<tr>
		<td><%=c.name%></td>
		<td><%=c.email%></td>
		<td><%= c.created_at.to_time.strftime('%e %B à %l:%M %p')%></td>			
		<td>
			<%= link_to "Edit" , edit_admin_user_path(c) , class:'btn btn-primary' %>  
		<%= link_to "Delete" , admin_user_path(c) , class:'btn btn-danger' , method: :delete , data: {confirm:"Confirmez cette suppression..."} %></td>
		
	</tr>
	<%end%>
</table>
<%= will_paginate @users %>
<%else%>
	<p>Aucun Utilisateur</p>
<%end%>

app/views/admin/users/new.html.erb
<h2>Add New User</h2>
<%= form_for [:admin, @user] do |f| %>
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |m| %>
		<div class="alert alert-danger"><%= m %></div>
	<%end%> <!-- end Do m -->
<%end%> <!-- end If -->
<div class="form-group col-md-4 pull-left">
	<%= f.label :'Nom Utilisateur' %>
	<%= f.text_field :name,class:'form-control' %>
</div>

<div class="form-group col-md-4 pull-left">
	<%= f.label :Email %>
	<%= f.text_field :email,class:'form-control' %>
</div>

<div class="form-group col-md-4 pull-left">
	<%= f.label :'Mot de passe' %>
	<%= f.password_field :password,class:'form-control' %>
</div>

<div class="form-group col-md-4 pull-left">
	<%= f.label :'Saisir à Nouveau le mot de passe'  %>
	<%= f.password_field :password_confirmation,class:'form-control' %>
</div>
<br>

<div class="form-group col-md-4 pull-right"><%= f.submit "Submit" , class:'btn btn-primary'  %>
	<%=  link_to "Cancel" , admin_users_path, class:'btn btn-default' %></div>
<%end%> <!-- end Do f -->